#! /usr/bin/env python
from __future__ import division

import rospy
from geometry_msgs.msg import Quaternion
from geometry_msgs.msg import Twist
from nav_msgs.msg import Odometry
from std_msgs.msg import Int32
from sensor_msgs.msg import JointState
from roboclaw_driver.msg import Stats
from geometry_msgs.msg import PoseWithCovarianceStamped
from tf.broadcaster import TransformBroadcaster
from tf.transformations import quaternion_from_euler, euler_from_quaternion
from math import sin, cos
from diff_drive.pose import Pose
from diff_drive import odometry

class OdometryNode:

    def __init__(self):
        self.odometry = odometry.Odometry()
        self.have_aggregate = [False, False]
	self.tick_aggregate = [[-1,-1], [-1,-1]]

    def main(self):
        self.odomPub = rospy.Publisher('odom', Odometry, queue_size=10)
        self.jointStatePub = rospy.Publisher('/joint_states_wheels', JointState, queue_size=10)
        self.tfPub = TransformBroadcaster()

        rospy.init_node('diff_drive_odometry')
        self.nodeName = rospy.get_name()
        rospy.loginfo("{0} started".format(self.nodeName))

        rospy.Subscriber("/roboclaw/stats", Stats, self.frontCallback)
        rospy.Subscriber("/roboclaw_2/stats", Stats, self.rearCallback)
        rospy.Subscriber("initialpose", PoseWithCovarianceStamped,
                         self.on_initial_pose)

        self.ticksPerMeter = int(rospy.get_param('~ticks_per_meter'))
        self.wheelSeparation = float(rospy.get_param('~wheel_separation'))
        self.rate = float(rospy.get_param('~rate', 10.0))
        self.baseFrameID = rospy.get_param('~base_frame_id', 'base_link')
        self.odomFrameID = rospy.get_param('~odom_frame_id', 'odom')
        self.encoderMin = int(rospy.get_param('~encoder_min', -32768))
        self.encoderMax = int(rospy.get_param('~encoder_max', 32767))

        self.odometry.setWheelSeparation(self.wheelSeparation)
        self.odometry.setTicksPerMeter(self.ticksPerMeter)
        self.odometry.setEncoderRange(self.encoderMin, self.encoderMax)
        self.odometry.setTime(rospy.get_time())

        rate = rospy.Rate(self.rate)
        while not rospy.is_shutdown():
            self.publish()
            rate.sleep()

    def publish(self):
        self.odometry.updatePose(rospy.get_time())
        now = rospy.get_rostime()
        pose = self.odometry.getPose()

        q = quaternion_from_euler(0, 0, pose.theta)
        self.tfPub.sendTransform(
            (pose.x, pose.y, 0),
            (q[0], q[1], q[2], q[3]),
            now,
            self.baseFrameID,
            self.odomFrameID
        )

        odom = Odometry()
        odom.header.stamp = now
        odom.header.frame_id = self.odomFrameID
        odom.child_frame_id = self.baseFrameID
        odom.pose.pose.position.x = pose.x
        odom.pose.pose.position.y = pose.y
        odom.pose.pose.orientation.x = q[0]
        odom.pose.pose.orientation.y = q[1]
        odom.pose.pose.orientation.z = q[2]
        odom.pose.pose.orientation.w = q[3]
        odom.twist.twist.linear.x = pose.xVel
        odom.twist.twist.angular.z = pose.thetaVel
        self.odomPub.publish(odom)

    def on_initial_pose(self, msg):
        q = [msg.pose.pose.orientation.x,
             msg.pose.pose.orientation.x,
             msg.pose.pose.orientation.x,
             msg.pose.pose.orientation.w]
        roll, pitch, yaw = euler_from_quaternion(q)

        pose = Pose()
        pose.x = msg.pose.pose.position.x
        pose.y = msg.pose.pose.position.y
        pose.theta = yaw

        rospy.loginfo('Setting initial pose to %s', pose)
        self.odometry.setPose(pose)

    def tickToRad(self, tick):
        return tick / (256*512) * 2 * 3.14159

    def sendWheelStates(self): # Only called when both callbacks have updated (potential issue with timing mismatches??)
        _l_tick_avg = (self.tick_aggregate[0][0] + self.tick_aggregate[1][0]) / 2
        _r_tick_avg = (self.tick_aggregate[0][1] + self.tick_aggregate[1][1]) / 2
        self.odometry.updateLeftWheel(_l_tick_avg)
        self.odometry.updateRightWheel(_r_tick_avg)
        self.have_aggregate = [False, False]
        # print("Tick Avgs: %s\t%s" % (_l_tick_avg, _r_tick_avg))
        # Update Joint states too
        jointStates = JointState()
        jointStates.header.stamp = rospy.Time.now()
        jointStates.name = ['ps_wheel_joint', 'pf_wheel_joint', 'sf_wheel_joint', 'ss_wheel_joint']
        jointStates.position = [-self.tickToRad(self.tick_aggregate[1][0]), \
                                -self.tickToRad(self.tick_aggregate[0][0]), \
                                self.tickToRad(self.tick_aggregate[0][1]), \
                                self.tickToRad(self.tick_aggregate[1][1])] # Note: tick aggregate order is [front/back][L/R], but naming is [port/starboard][fore,stern]
        self.jointStatePub.publish(jointStates)

    def frontCallback(self, msg):
        self.have_aggregate[0] = True
	self.tick_aggregate[0] = [msg.m1_enc_val, msg.m2_enc_val]
	if self.have_aggregate[0] and self.have_aggregate[1]:
            self.sendWheelStates()

    def rearCallback(self, msg):
        self.have_aggregate[1] = True
        self.tick_aggregate[1] = [msg.m1_enc_val, msg.m2_enc_val]
        if self.have_aggregate[0] and self.have_aggregate[1]:
            self.sendWheelStates()

if __name__ == '__main__':
    try:
        node = OdometryNode()
        node.main()
    except rospy.ROSInterruptException:
        pass
